### ISSUE TITLE
boot2docker on Mac

### ISSUE THREAD

**Issue by adamgoose** [shincoder/homestead-docker#1]
Have you tried using this on a Mac with boot2docker? I can get the instance running, but since the docker container runs inside its own VM, there are so many port forwards. Any idea on how to access nginx on the docker container through the boot2docker VM?

**Comment by jaouadk** [comment]
@adamgoose : I mapped port 2222 to ssh port 22 inside the container.

What you should do add a portmap to the VM to expose the ssh port to your host.

This might help: http://stackoverflow.com/questions/23014684/how-to-get-ssh-connection-with-docker-container-on-osxboot2docker
