### ISSUE TITLE
Please help me get this to work on Mac

### ISSUE THREAD

**Issue by digitalit** [shincoder/homestead-docker#10]
I cant get it to work on my mac.

ssh gives me access denied and no web och mysql connection

Thank you

**Comment by jaouadk** [comment]
Can you post the output of `docker ps` and `docker logs homestead_container_id`

As for accessing the database container, use can do:

``` shell
docker exec -it db_container_id mysql
```

**Comment by jaouadk** [comment]
Docker on Mac OS works inside a VM, so instead of using the standard `172.17.0.1` ip address, you should use the IP assigned by docker machine when you started the VM.

I think `docker-machine ip default` should output the IP assigned.

The same IP can be used to ssh into the container and connect to the database.

**Comment by digitalit** [comment]
What is the benefit of running laravel dev in this compared to the vagrant homestead?

**Comment by jaouadk** [comment]
Vagrant is slow, docker containers are very fast. If you have a 16G RAM, probably you won't notice this, but this was the case for me.

**Comment by digitalit** [comment]
docker ps
CONTAINER ID        IMAGE                 COMMAND             CREATED              STATUS                         PORTS                                                                                          NAMES
463ee022d62e        shincoder/homestead   "/run.sh"           About a minute ago   Up About a minute              0.0.0.0:9876->9876/tcp, 0.0.0.0:35729->35729/tcp, 0.0.0.0:2222->22/tcp, 0.0.0.0:8000->80/tcp   homesteaddocker_web_1
c1c876b02e82        tutum/mariadb         "/run.sh"           About a minute ago   Restarting (0) 6 seconds ago   0.0.0.0:33060->3306/tcp                                                                        homesteaddocker_mariadb_1

**Comment by digitalit** [comment]
![skarmavbild 2016-02-16 kl 22 55 33](https://cloud.githubusercontent.com/assets/6569136/13092467/67f53cfe-d500-11e5-92f2-c197b08be470.png)

**Comment by digitalit** [comment]
Is it better for me to stick with vagrant?

**Comment by jaouadk** [comment]
Yes, I think so. Unless you notice any lags.

**Comment by digitalit** [comment]
Ok thank you

Skickat från min iPhone
