### ISSUE TITLE
Fatal error: Non-static method Redis::keys() cannot be called statically

### ISSUE THREAD

**Issue by cezarpavelski** [shincoder/homestead-docker#14]
By using Redis through the alias \Redis in Laravel, the below error occurs:

Fatal error: Non-static method Redis::keys() cannot be called statically

**Comment by jaouadk** [comment]
This has nothing to do with the container.

Redis class name conflicts with an existing one, either you change the alias of the facade in app.php, or reference the complete Laravel namespace.

try this:

``` php
Illuminate\Support\Facades\Redis::keys()
```

**Comment by cezarpavelski** [comment]
OK, thanks
