### ISSUE TITLE
Cange php.ini

### ISSUE THREAD

**Issue by digitalit** [shincoder/homestead-docker#15]
Hi,

Just love this project, made me leave Vagrant.

I have added 
`sed -i "s/post_max_size = .*/post_max_size = 99M/" /etc/php/7.0/fpm/php.ini`
`sed -i "s/upload_max_filesize = .*/upload_max_filesize = 99M/" /etc/php/7.0/fpm/php.ini`

in provision.sh but i don know how to make it take effect?

Thank you.

**Comment by jaouadk** [comment]
Hey @digitalit,

Glad you like it.

Since you are changing the provision script directly, You should rebuild the image for the changes to take effect.

`docker build -t shincoder/homestead:php7.0 .`

and then:

`docker-composer up -d --force-recreate`

This will recreate your containers.

**Comment by digitalit** [comment]
Thank you so much @shincoder
