### ISSUE TITLE
Export/ save container

### ISSUE THREAD

**Issue by digitalit** [shincoder/homestead-docker#17]
When using Vagrant i could export an backup of my VM machine and load i locally or from my own github. Is it possible to do so with Docker?

**Comment by jaouadk** [comment]
Yes it's possible `docker export CONTAINER_ID > /home/export.tar`
see also how to import the exported tar archive https://docs.docker.com/engine/reference/commandline/import/

**Comment by digitalit** [comment]
Thank you
