### ISSUE TITLE
homestead-docker vs laradock

### ISSUE THREAD

**Issue by digitalit** [shincoder/homestead-docker#18]
I see a lot of "Deprecated in favor of laradock. Will you continue to support this homestead-docker?

I guess the whole purpose with the laradock concept of having every service in different containers and only serving one laravel project is so one could deploy "the whole package" to an production droplet?

For now i will only use Docker for development so i really like the idea of having only two containers and be able to have all my projects in two containers.

I really like to have your opinion on this @shincoder :)

**Comment by jaouadk** [comment]
Yes, definitely, I am using "homestead-docker" on a daily basis, and will continue tweaking it as needed.

As for production, `shincoder/homestead:php7.0` can definitely be used with some tweaks here and there, it all depends on your app. Some prefer to separate services in multiple containers (I do), some don't.

But for development, why bother?

I other situations, you'll want to have a replica of your production environment on your local machine, this prevents unexpected scenarios when deploying.

**Comment by digitalit** [comment]
Great, then i will continue trying to get xdebug working so i can skip vagrant totally.

Thank you @shincoder
