### ISSUE TITLE
Not an issue - just a Question

### ISSUE THREAD

**Issue by digitalit** [shincoder/homestead-docker#19]
Hi,

I have some Joomla and WP sites that i ran in an Vagrantbox and since i would like to leave Vagrant/WM totally i came across this docker proj: https://github.com/rivenvirus/apache-php-multisite

Now i got this working but since i don't want to fiddle with ports other than 80 i cant run Laravel, Nginx, MariaDB sites att the same time as WP, Apache, MySQL sites. 

When running Vagrant i had different IP:s on the Vagrant machines so there were no problems with port 80. This might be impossible to solve with Docker but if i could i really would like to mix these two dockers in some way.

Is this possible?

**Comment by jaouadk** [comment]
homestead-docker's stack is capable of running wordpress. just add it as another app to your current container.

see read me on how to add another virtual host.

**Comment by digitalit** [comment]
Yes that was my first thought but since my Swedish provider for non Laravel sites runs Apache, PHP 5.6 and MySQL i thought i should try to replicate that environment as close as i could.

Maybe this is unnecessary and if so i would be more than happy to run all projects in your docker.

I guess the big problem is that if i run MariaDB in dev and export to prod that runs MySQL this will be an problem. Maybe i can run two sql containers side by side?

What is your opinion?

**Comment by jaouadk** [comment]
Yes you can add another Mysql container see this: https://github.com/docker-library/mysql

Just set the proper configuration in your wordpress config file and everything should work fine.

**Comment by digitalit** [comment]
i just need to chose different porst right? 

<pre>ports:
        - "33060:3306"</pre>

**Comment by digitalit** [comment]
Do you think this would work?

<pre>### MariaDB Container #########################################
mariadb:
    image: tutum/mariadb
    restart: always
    ports:
        - "33060:3306"
    environment:
        MARIADB_USER: admin # cannot be changed ( for info. only )
        MARIADB_PASS: root
    volumes:
        - ~/dc/apps/volumes/mariadb:/var/lib/mysql # database files
### MySQL Container #########################################
 mysqldb:
    image: mysql:5.7
    restart: always
    ports:
        - "33068:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - ~/dc/apps/volumes/mysqldb:/var/lib/mysql # database files</pre>

**Comment by jaouadk** [comment]
Yes, this config should work.

**Comment by digitalit** [comment]
Unfortunately this didn't work.

Some WP sites and all Joomla sited prior to version 3.5 doesn't  work with PHP7.

Any tip would be appreciated.

**Comment by jaouadk** [comment]
Try the other image which works with php 5.6

`shincoder/homestead:php5.6`

**Comment by digitalit** [comment]
Great!
I suspect that my Joomla sites wants Apache instead of Nginx.

Is it possible to run Apache instead of Nginx?

**Comment by jaouadk** [comment]
Change the provision script accordingly. then configure your virtual host, and you're good to go.

Or find another project offering the stack as a docker container.

**Comment by digitalit** [comment]
im afraid im lacking the skills.

Could i pay you to edit the provision.sh so i can use Apache and multi sites?

**Comment by shincoder** [comment]
How much can you afford?

**Comment by digitalit** [comment]
This is what i what to replicate: http://www.engqvistbygg.se/php.php

Well name your price and i will check in my wallet :)

**Comment by shincoder** [comment]
let's continue this discussion in email, send me your email address.

**Comment by digitalit** [comment]
great, i made an contact from your website.

Hope you got my mail :)

**Comment by shincoder** [comment]
nothing yet. send to jaouad.elmoussaoui@gmail.com
