### ISSUE TITLE
connecting to the database

### ISSUE THREAD

**Issue by dydx** [shincoder/homestead-docker#2]
forgive me for being dense, but how do I connect my laravel app to the database in the other container?

**Comment by dydx** [comment]
I've managed to get connected and whatnot using the `mariadb` container's actual IP address: 172.17.0.5, but I see in other examples from Docker that I should be able to just say `DB_HOST=mariadb` in my .env, but I've tried `mariadb`, `homesteaddocker_mariadb_1`, `localhost`, and I get errors about not being able to connect.

**Comment by dydx** [comment]
Submitted a [pull request](https://github.com/shincoder/homestead-docker/pull/3) to solve this.

**Comment by jaouadk** [comment]
@dydx Thanks, Referencing DB credentials directly in the .env file will work just fine, you won't be forced to use the same environment names in your production app.

Anyway, Merging!

If you want to do it my way then use this:

``` shell
DB_HOST = 172.17.42.1 ( see bellow )
DB_PORT = 3306 ( or custom port )
DB_NAME = db_name ( you should create it first )
DB_USER = admin ( cannot be changed )
DB_PASSWD = root ( same as docker_compose.yml file )
```

Sometimes, the connection does not work with 127.0.0.1 or localhost, you should use docker's internal IP, for me it's 172.17.42.1, it should be the same for you. Ifconfig to find it.

**Comment by dydx** [comment]
That way works, but as you mentioned the IP is subject to change.

Now that the web container and the database container are linked, you can use the more idiomatic way of just specifying:`DB_HOST = mariadb` and it'll work between builds with no issue of IP reassigning.
