### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by digitalit** [shincoder/homestead-docker#20]
When i'm running xdebug i get "504 Gateway Time-out" and i wonder if there is an way to extend this somehow?

**Comment by jaouadk** [comment]
It's about a long running xdebug session. We'll need to increase timeout in nginx.

**Comment by digitalit** [comment]
Just that i'm not sure where to do this, i guess somewhere in the provision.sh but i'm afraid i will break something :)

**Comment by jaouadk** [comment]
No worries, I'll handle it, but be patient.

**Comment by digitalit** [comment]
Sweet.

**Comment by jaouadk** [comment]
I'll add these to the container later when I find the time.

but for now, ssh into the container `ssh -p 2222 homestead@localhost`, and add this line to `/etc/nginx/fastcgi.conf`

```
fastcgi_read_timeout 600;
```

then restart your services:
`supervisorctl restart php-fpm7.0 && supervisorctl restart nginx`

**Comment by jaouadk** [comment]
Try also to disable xdebug auto restart `xdebug.remote_autostart=0;` if the problem persists.

**Comment by digitalit** [comment]
Worked like a charm :)

**Comment by jaouadk** [comment]
Happy to hear that.
