### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by digitalit** [shincoder/homestead-docker#22]
I get "413 Request Entity Too Large" when trying to upload an 1.8MB image.

Should i change client_max_body_size like this: http://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/

**Comment by jaouadk** [comment]
Yes that should work.

php's `upload_max_filesize` is by default **2mb** and **8mb** for `post_max_size`, change them accordingly.

Restart your services for the changes to be applied.

**Comment by digitalit** [comment]
Those php.ini things were already set to 99MB so i did this:

ssh -p 2222 homestead@localhost

sudo nano /etc/nginx/nginx.conf

in the beginning of http i added client_max_body_size 99M;

like so:

http {
        client_max_body_size 99M; 

Now it's working :)
