### ISSUE TITLE
How to connect MySQL WorkBench

### ISSUE THREAD

**Issue by jeastman19** [shincoder/homestead-docker#23]
Hello.

I have a Mac with macOS Sierra Version 10.12.1.

I modified the script to ejcute MariaDB instead of MySQL.

Now I'm trying to connect to the database from MySQL WorkBench but which are not necessary parameters, any ideas please?

Greetings.

**Comment by jaouadk** [comment]
Hi, sorry for not replying sooner,

This project already uses Mariadb as a separate container.

To connect to mariadb use docker IP or localhost ( ifconfig to get it, it's usually 172.17.0.1 ), the username, password and port are defined in docker-compose file.

**Comment by jeastman19** [comment]
Hello shincoder.

I modify the file docker-compose.yml  to use the tutum / mysql image, and enter into the container with the instruction:

-it homestead_mysql_1 docker exec mysql

I can manage the DBMS.

What I can not connect from the host using MySQL Workbench.

I used the IP address of the container and the localhost.

Thank you very much for your time greetings.

**Comment by jaouadk** [comment]
Are you using docker-machine to manage docker in your Mac?

If so, you need to use docker machine ip: `docker-machine ip`

**Comment by jeastman19** [comment]
Hello Jaouad.

Thanks for the support.

I commented, I am using Docker for Mac, which requires no longer use docker-machine.

https://docs.docker.com/docker-for-mac/

I'm pretty novice at Docker, initially was starting to study it in GNU / Linux and now I've changed to Mac I'm studying to start using it in my work.

I mention ...

In writing:

---

**_docker exec bash -it homestead_mysql_1_**

I can enter without problems

---

and writing

**_docker -it homestead_mysql_1 docker exec mysql_**

I can manage MySQL without problems from the inside.

---

Now, the problem is from the outside, I have added a user, I have given all privileges to it, I have configured MySQL for remote access, but still can not get that MySQL Workbench is still connected not I'm doing wrong.

Any recommendation is welcome and timely.

Greetings.

**Comment by jaouadk** [comment]
Paste the output of `docker ps` .

**Comment by jeastman19** [comment]
`49b85de0e11c        shincoder/homestead:php7.0   "/usr/bin/supervisord"   10 hours ago        Up 11 hours         0.0.0.0:80->80/tcp, 0.0.0.0:9876->9876/tcp, 0.0.0.0:35729->35729/tcp, 0.0.0.0:2222->22/tcp   homestead_web_1
c0ccaccc1cbd        tutum/mysql                  "/run.sh"                10 hours ago        Up 45 seconds       0.0.0.0:2223->22/tcp, 0.0.0.0:33060->3306/tcp                                                homestead_mysql_1`

**Comment by jaouadk** [comment]
Did you instruct mysqlWorkbench to use port 33060 instead of the default 3306 ?

**Comment by jaouadk** [comment]
if a direct connection is not working for you, try the ssh tunnel via port 2223, I see tutum/mysql exposing ssh port.

**Comment by jeastman19** [comment]
Ok, thank you very much, I'll try and then comment the results.

Greetings.
