### ISSUE TITLE
cant run serve.sh: permission denied

### ISSUE THREAD

**Issue by orhan-swe** [shincoder/homestead-docker#28]
I've got problem with permission when running serve.sh script:

```
homestead@0b05195898f3:/$ sudo ./serve.sh myapp.dev /apps/frid/server/public
[sudo] password for homestead:
./serve.sh: line 40: /etc/nginx/sites-available/myapp.dev: Permission denied
ln: failed to create symbolic link '/etc/nginx/sites-enabled/myapp.dev': Permission denied
nginx: stopped
nginx: started
```

this is how permissions for sites-available look like:
```
homestead@0b05195898f3:/$ ll /etc/nginx/sites-available/
total 4
drwxr-xr-x 2 root root    0 Jan 16 16:20 ./
drwxr-xr-x 1 root root 4096 Jan 16 15:33 ../
```

It seems like this is first time this is being reported. May be because I am on windows, my volumes mapping looks like this:
```
- ~/docker/homestead-custom/volumes/nginx/sites-available:/etc/nginx/sites-available
- ~/docker/homestead-custom/volumes/nginx/sites-enabled:/etc/nginx/sites-enabled 
```

**Comment by orhan-swe** [comment]
For some reason my c drive was not shared with docker. Once I updated the docker settings and made the c drive shared again, this disappeared. 
A docker update was run earlier today and I think that this setting was reset and the c drive stopped being shared and that is when I got this error..

For other with same issue, to change this setting you need to:
-> right click on the whale ( the whale may be hidden in the Notifications area ) 
-> choose settings 
-> shared drives 
-> select c drive 
-> apply

I am closing this issue

**Comment by jaouadk** [comment]
If you didn't do the job yourself, I wouldn't be able to help you, Windows always gives me headaches !!!

Didn't use for a long long time!

Glad you figured this out.
