### ISSUE TITLE
How to connect on mysql?

### ISSUE THREAD

**Issue by jeffersonest** [shincoder/homestead-docker#33]
Iḿ trying to connect to mysql, but iḿ receiving failed!

the application is ok, but de DB is failed...

Host: localhost:3306
user: root
password:

**Comment by aaronmaynard** [comment]
There are many instances where MySQL will need a password.  I know for AWS you will be outta luck if you didn't set a password for verification.  A simple `1234` will do, otherwise it will always fail on connect.

**Comment by jeffersonest** [comment]
The solution:  

1- execute:
   docker ps
2- get the mysql docker ID, and execute:
   docker exec -it [docker id] bash
3 - into the container execute: 
   cat /etc/hosts
4 - get the last line ip address
    **172.17.0.2**  (example)
5 - use this ip to connect on mysql server
