### ISSUE TITLE
Upgrade PHP 7.2

### ISSUE THREAD

**Issue by jeffersonest** [shincoder/homestead-docker#34]
I need some help to upgrade php to 7.2 version.

**Comment by jaouadk** [comment]
As simple as replacing any occurrence of php 7.1 with 7.2 in these files:
```provision.sh``` ```serve.sh``` and ```supervisor.conf```

Then rebuild the image.

I might do it later today if I find some time.

**Comment by jeffersonest** [comment]
Thank's!
