### ISSUE TITLE
Nginx Sites-enabled problem

### ISSUE THREAD

**Issue by jeffersonest** [shincoder/homestead-docker#35]
2 months ago I ran the docker and created the 'default' file inside the 'sites-available' folder, but now it does not create any more, was there any change in the process?

**Comment by jaouadk** [comment]
Seems something wrong with permissions. No changes made to the image though.

Try to use the serve.sh script as indicated in the README.

**Comment by jeffersonest** [comment]
Thank's solved my problem!
