### ISSUE TITLE
Couple of fixes were needed

### ISSUE THREAD

**Issue by EdgarsK** [shincoder/homestead-docker#5]
Ran into few problems while installing, required these changes in start of the provision file :
# fix for - dpkg-reconfigure: unable to re-open stdin: No file or directory

export DEBIAN_FRONTEND=noninteractive
# fix for  - invoke-rc.d: policy-rc.d denied execution of start.

printf "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d
# fix for - The following packages cannot be authenticated

locale-gen en_US.UTF-8
export LANG=en_US.UTF-8
apt-key update

**Comment by jaouadk** [comment]
Thanks @EdgarsK , you can submit your PR.
