### ISSUE TITLE
How to connect to database?

### ISSUE THREAD

**Issue by BennyAlex** [shincoder/homestead-docker#52]
Hello,

I dont know how to connect to the database. It looks like only the web container is available using HTTP.

```
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                             NAMES
b2f66165c50a        shincoder/homestead:php7.3   "/usr/bin/supervisord"   21 minutes ago      Up 21 minutes       9876/tcp, 35729/tcp, 0.0.0.0:2222->22/tcp, 0.0.0.0:8000->80/tcp   homestead-docker_web_1
c713ffcce910        mysql:5.7                    "docker-entrypoint.s…"   2 hours ago         Up 11 minutes       3306/tcp, 33060/tcp
```

A little guide in the readme would be really great.

**Comment by jaouadk** [comment]
Hey @BennyAlex, Sorry for the late response, actually there is a small snippet in the readme that shows how to connect to the database:

mysql host is exposed to the linked app container using host ```mysql```, use this in your ```.env```

```
DB_HOST=mysql
DB_PORT=3306
DB_USERNAME=root
DB_PASSWORD=
```

If you want to connect to the database from the outside, expose port ```3306``` in ```docker-compose.yml``` file.
