### ISSUE TITLE
php5.6 and mailparse

### ISSUE THREAD

**Issue by alan614** [shincoder/homestead-docker#6]
I've noticed that the php version here has fallen behind, it's still at 5.9.9 whereas in the vagrant one it's at 5.6.15, could be a result of the ondrej ppa being removed(though what I've encountered is that putting it back required a public key update)? 

Also, the latest mailparse of pecl requires php 7 (so this breaks during the image build as well), so specifying the version number might be required, however I found that after updating to php 5.6, mailparse is searched in /usr/lib/php5/20131226/mailparse.so whereas the current mailparse would still be location in folder /url/lib/php5/2012****/

**Comment by jaouadk** [comment]
I had few problems getting ondrej ppa to work, add-apt-repository breaks with non-UTF-8 locales. I fixed it locally, just need to push changes.

As for php7, I'll create a new branch for it. Should be easy to setup I think.

Thanks @alan614

**Comment by alan614** [comment]
thanks! I'm actually wondering how to get mailparse to work with php 5.6, or maybe it would compile now if the build starts off with the ondrej ppa from the start

**Comment by jaouadk** [comment]
They just released version 3.0.0 on the 23rd requiring php >= 7.0.

for php 5.6 you need 2.x

I'll see what I can do.

**Comment by jaouadk** [comment]
mailparse 2.1.6 with ondrej ppa (php 5.6) added to the provisioning script. (3af2c9fa313574546e2edc8362a5521d7b5514c8)
![mailparse](https://cloud.githubusercontent.com/assets/6833740/12139896/67ee06ca-b45b-11e5-9a2c-d27dfd447b9f.png)

Rebuild your image
