### ISSUE TITLE
One question: how can I connect me to mariadb?

### ISSUE THREAD

**Issue by tanrax** [shincoder/homestead-docker#8]
It would be interesting to clarify it :)

**Comment by jaouadk** [comment]
Here are the env variables I use in the .env file:

```
DB_HOST=172.17.0.1
DB_PORT=33060
DB_DATABASE=changeMe
DB_USERNAME=admin
DB_PASSWORD=root
```

since the port is not specified in config/database.php, add it to your mysql connection:

``` php
'host'      => env('DB_HOST', 'localhost'),
'database'  => env('DB_DATABASE', 'forge'),
'port'      => env('DB_PORT', 3306),
```

if you use phpmyadmin, add those credentials to `config.inc.php` and you'll be able to connect and create your databases.

If not: `docker exec -it replace_with_mariadb_container_id mysql`, once inside: `create database myDatabase`

**Comment by tanrax** [comment]
I encounter the following problem when I run artisan

```
SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading initial communication packet', system error: 0
```

There the `mysql` command?

**Comment by tanrax** [comment]
```
docker exec -it replace_with_mariadb_container_id mysql
```

say

```
Error response from daemon: no such id: replace_with_mariadb_container_id
```

**Comment by jaouadk** [comment]
You didn't replace that string that says `replace_with_mariadb_container_id` with mariadb container id.

`docker ps` to get the container id, then run the command with the id provided.

**Comment by tanrax** [comment]
It does not work :( I've done everything from zero. When I run it just ignores it.

```
$ docker exec -it 862cef2dd89e mysql
$
```

**Comment by jaouadk** [comment]
That's weird !!!! It works for me.

```
$ docker exec -it 33dfc3058655 mysql 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 118
Server version: 10.1.5-MariaDB-1~trusty-log mariadb.org binary distribution

Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>
```
